### ISSUE TITLE
Overlay not showing

### ISSUE THREAD

**Issue by Reoxy** [Woyken/pixelplanet.fun-OverlayPicture#56]
I'm an android user, I'm mobile and when I installed this overlay plugin, it was working fine at first, but in early 2022, it didn't work even though I refreshed the page a few times. please let me know if there is a solution <3

**Comment by Woyken** [comment]
Which browser are you using on Android that supports extensions?
I just downloaded Kiwi browser for a quick test, seems to work

**Comment by Reoxy** [comment]
> Which browser are you using on Android that supports extensions?
> I just downloaded Kiwi browser for a quick test, seems to work
> 

yes it works at first but when i refresh the page the overlay disappears is there an update released?

**Comment by Reoxy** [comment]
> Which browser are you using on Android that supports extensions?
> I just downloaded Kiwi browser for a quick test, seems to work
> 

problem solved, thanks a lot :)

**Comment by Reoxy** [comment]
> Which browser are you using on Android that supports extensions?
> I just downloaded Kiwi browser for a quick test, seems to work
> 

problem solved, thanks a lot :)

**Comment by Woyken** [comment]
I did fix another issue I ran into. Sometimes userscript could get loaded before page itself, that would cause it to fail to load.
Different browsers and different userscript managers can act in different ways, that's why I asked which browser were you using. So I could test it if it works on my end.

Anyway, I'm glad it works for you now.
Closing this issue
