### ISSUE TITLE
Using custom server for file hosting, some options disappear

### ISSUE THREAD

**Issue by Junifil744** [Woyken/pixelplanet.fun-OverlayPicture#88]
Basically, using a discord link for file hosting and using on the overlay works fine but using my own server, to which ive put a file on
(https://middlemouse.click/pixelqbc/template.png if you need it)
Simply makes the Smol Pixels, Convert colors and Auto color buttons disappear.
Might be a bug or something related to my image but im just wondering in general
The overlay still works fine though, those buttons are just missing

Normal file / link
![image](https://github.com/Woyken/pixelplanet.fun-OverlayPicture/assets/84987818/79807b6e-4ade-413c-b771-f8e62996fc85)

Link from my server
![image](https://github.com/Woyken/pixelplanet.fun-OverlayPicture/assets/84987818/3dd7c685-2d27-4b32-87d3-6b7da01a3d96)

**Comment by Woyken** [comment]
This usually happens due to CORS limitations.
If server that's hosting the image specifies that it doesn't allow other websites to access it's content, then we have very limited access, I'll just display the image directly and scripts cannot read the image's contents. So there is no way of knowing what is being displayed from the script side, no modifications possible.
It's just browser security limitation.

**Comment by Junifil744** [comment]
Ah I get it, yeah that would make sense. Alright thanks!
